export const PRODUCT_FETCH = 'PRODUCT_FETCH';
export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL';
export const PRODUCT_ADD = 'PRODUCT_ADD';
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL';
export const CATEGORY_FETCH = 'CATEGORY_FETCH';
export const CATEGORY_FETCH_FAIL = 'CATEGORY_FETCH_FAIL';